version: 2.1

default_version: &default_version 1.8.1

jobs:
  build:
    parameters:
      version:
        description: Elixir Version
        type: string
        default: *default_version
    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>
    working_directory: ~/app
    environment:
      MIX_ENV: test

    steps:
      - checkout  # check out source code to working directory
      - run: wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.14.1/nats-streaming-server-v0.14.1-linux-amd64.zip
      - run: unzip nats-streaming-server-v0.14.1-linux-amd64.zip
      - run:
          command: ./nats-streaming-server-v0.14.1-linux-amd64/nats-streaming-server
          background: true
      - restore_cache:
          keys:
            - build-<<parameters.version>>
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - save_cache:
          key: build-<<parameters.version>>
          paths:
          - "deps"
          - "_build"
          - "~/.mix"
      - run: mix test
  lint:
    parameters:
      version:
        description: Elixir Version
        type: string
        default: *default_version
    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>
    working_directory: ~/app
    steps:
      - checkout  # check out source code to working directory
      - restore_cache:
          keys:
            - lint-<<parameters.version>>-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: lint-<<parameters.version>>-{{ checksum "mix.lock" }}
          paths:
          - "deps"
          - "_build"
          - "~/.mix"

workflows:
  version: 2.1
  testing_all_versions:
    jobs:
      - build:
          name: "Test Elixir 1.8.1"
          version: 1.8.1 
      - build:
          name: "Test Elixir 1.7.4"
          version: 1.7.4
      - build:
          name: "Test Elixir 1.6.6"
          version: 1.6.6
      - lint:
          name: "Check formatting and Types"